---
type: qemu
description: Eltex vESR
name: vESR
cpulimit: 1
icon: Router.png
cpu: 4
ram: 3072
qemu_nic: e1000
ethernet: 4
eth_format: gi1/0/{1}
console: telnet
shutdown: 1
qemu_arch: x86_64
qemu_version: 2.12.0
qemu_options: -machine type=pc,accel=kvm -serial mon:stdio -no-user-config -nodefaults -rtc base=utc -vga>
...
